In [ ]:
# Graph
'''
Graphs with nodes and edges

'''

In [131]:
import numpy as np

class Node(object):
    #nodes store value and the edges which connected to it
    def __init__(self, value):
        self.value=value
        self.edges=[]
        
class Edge(object):
    #value of edges represent the different types of relations between nodes
    #directed graph need to record the direction between the nodes
    def __init__(self, value, node_from, node_to):
        self.value=value
        self.node_from=node_from
        self.node_to=node_to
               
class Graph(object):
    #contains lists of nodes and edges
    #if the graph is disconnected, not every node will be tied to an edge,
    #should store a list of nodes
    def __init__(self, nodes=[], edges=[]):
        self.nodes=nodes
        self.edges=edges
        
    #as we store both nodes and edges of the graph
    #when insert a node or edge, both the list of nodes and edges need keep updated
    #assumne each value is unique
    def insert_node(self, node_val):
        #generate new node
        new_node=Node(node_val)
        #update the node list
        self.nodes.append(new_node)
                             
    def insert_edge(self, edge_val, from_val, to_val):
        #generate new edge
        #new_edge=Edge(edge_val, from_val, to_val) 
        #update the edge list
        #check the statue by checking the node statu
        #in case the node not exist, check the node frist
        from_check=None
        to_check=None
        for node in self.nodes:
            #node existed
            if node.value==from_val:
                from_check=node
            if node.value==to_val:
                to_check=node
        if from_check==None:
            #not collipsed
            #generate new node and update the node list
            from_check=Node(from_val)
            self.nodes.append(from_check)
        if to_check==None:
            to_check=Node(to_val)
            self.nodes.append(to_check)   
        #connect the edges to nodes
        new_edge=Edge(edge_val, from_val, to_val)
        from_check.edges.append(new_edge)
        to_check.edges.append(new_edge)
        self.edges.append(new_edge)
            
    def get_nodes(self):
        node_list=[]
        for each in self.nodes:
            node_list.append(each.value)

        return node_list
    
    def get_edges(self):
        edge_list=[]
        for each in self.edges:
            edge=(each.value, each.node_from, each.node_to)
            edge_list.append(edge)
        return edge_list
    
    def get_adjacency_matrix(self):
        #rectangular matrix
        #find the range of the index
        max=0
        if len(self.nodes):
            for node in self.nodes:
                if node.value>max:
                    max=node.value
        
        #max as the biggest number of nodes
        #decide the size of matrix
        
        #adj_matrix=[[0 for i in range(max+1)] for j in range(max+1)]
        adj_matrix=np.zeros((max+1)*(max+1), dtype=int).reshape((max+1,max+1))
        
        for edge in self.edges:
            #print('{} {} {} '.format(edge.node_from, edge.node_to, edge.value))
            adj_matrix[edge.node_from][edge.node_to]=edge.value
        
        return adj_matrix
        

In [132]:
graph = Graph()
graph.insert_edge(100, 1, 2)
graph.insert_edge(101, 1, 3)
graph.insert_edge(102, 1, 4)
graph.insert_edge(103, 3, 4)

In [133]:
print(graph.get_nodes())

[1, 2, 3, 4]


In [134]:
# Should be [(100, 1, 2), (101, 1, 3), (102, 1, 4), (103, 3, 4)]
print(graph.get_edges())

# Should be [[0, 0, 0, 0, 0], [0, 0, 100, 101, 102], [0, 0, 0, 0, 0], [0, 0, 0, 0, 103], [0, 0, 0, 0, 0]]
print(graph.get_adjacency_matrix())

[(100, 1, 2), (101, 1, 3), (102, 1, 4), (103, 3, 4)]
[[  0   0   0   0   0]
 [  0   0 100 101 102]
 [  0   0   0   0   0]
 [  0   0   0   0 103]
 [  0   0   0   0   0]]
